apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-pod-reader
  namespace: spark-streaming-jobs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]