apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-pod-reader-binding
  namespace: spark-streaming-jobs
subjects:
- kind: ServiceAccount
  name: spark-service-account
  namespace: spark-streaming-jobs
roleRef:
  kind: Role
  name: spark-pod-reader
  apiGroup: rbac.authorization.k8s.io