apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-role-binding
  namespace: spark-streaming-jobs
subjects:
- kind: ServiceAccount
  name: spark-operator
  namespace: spark-streaming-jobs
roleRef:
  kind: Role
  name: spark-operator-role
  apiGroup: rbac.authorization.k8s.io