apiVersion: 'sparkoperator.k8s.io/v1beta2'
kind: SparkApplication
metadata:
  name: poc-test-v1
  namespace: spark-streaming-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 'rutvikdocker7399/airlines-data-analytics:streaming-jobs-v0.0.1'
  imagePullPolicy: Always
  imagePullSecrets: ['airlines-data-analytics-cred']
  sparkVersion: '3.4.0'
  restartPolicy:
    type: Always
    onFailureRetryInterval: 10
    onSubmissionFailureRetryInterval: 20
  sparkConf:
    "spark.kubernetes.file.upload.path": "/opt/spark/work-dir"
  hadoopConf:
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
  mainApplicationFile: 'local:///opt/spark/work-dir/airlines_data_analytics/src/jobs/spark_streaming.py'
  driver:
    cores: 1
    coreLimit: '1000m'
    memory: '700m'
    labels:
      version: 3.4.0
    serviceAccount: 'spark-operator-spark'
  executor:
    cores: 1
    coreLimit: '1000m'
    instances: 1
    memory: '1500m'
    labels:
      version: 3.4.0
    serviceAccount: 'spark-operator-spark'